name: "Run typedoc and publish to pages"

on:
  workflow_call:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build documentation
        uses: algorandfoundation/algokit-shared-config/.github/actions/generate-typescript-docs@main
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: github-pages-docs
          path: docs/_html
          retention-days: 1

  publish-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages-docs
          path: docs/downloaded

      - name: Deploy to GitHub Pages
        uses: algorandfoundation/algokit-shared-config/.github/actions/publish-docs@main
        with:
          artifact_path: docs/downloaded
