name: Build and Publish Documentation

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version to use
        required: false
        type: string
        default: 22.x

permissions:
  pages: write
  id-token: write

jobs:
  build_docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml
            docs/pnpm-lock.yaml

      - name: Fetch root dependencies
        shell: bash
        run: pnpm fetch --frozen-lockfile --prod=false

      - name: Install root dependencies
        shell: bash
        run: pnpm install --frozen-lockfile --prod=false --offline

      - name: Fetch docs dependencies
        shell: bash
        run: pnpm --dir docs fetch --frozen-lockfile --prod=false

      - name: Install docs dependencies
        shell: bash
        run: pnpm --dir docs install --frozen-lockfile --prod=false --offline

      - name: Build documentation
        shell: bash
        run: pnpm --dir docs run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/dist

  deploy_docs:
    name: Deploy Documentation
    needs: build_docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
