on:
  workflow_call:

jobs:
  check_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x

      - name: Check docs are up to date
        shell: bash
        run: |
          pnpm install --frozen-lockfile --ignore-scripts
          pnpm run generate:code-docs
          git add -N .
          git diff --exit-code --name-only
