on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 22.x
      working-directory:
        required: false
        type: string
        default: '.'
      build-path:
        required: false
        type: string
        default: build
      artifact-name:
        required: false
        type: string
        default: package
      static-site:
        required: false
        type: boolean
        default: false
      static-site-env-prefix:
        required: false
        type: string
        default: VITE
      pre-run-script:
        required: false
        type: string
      sample-env-path:
        required: false
        type: string
        default: .env.sample
    secrets:
    outputs:
      artifact-name:
        description: Name of the artifact created by this workflow
        value: ${{ inputs.artifact-name }}

jobs:
  build-zip:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: pnpm
          cache-dependency-path: ${{ format('{0}/pnpm-lock.yaml', inputs.working-directory) }}

      - name: Pre-run
        if: ${{ inputs.pre-run-script }}
        run: ${{ inputs.pre-run-script }}

      - if: ${{ inputs.static-site }}
        run: sed -n 's/\(${{ inputs.static-site-env-prefix }}_[A-Z0-9_]\+\)=\(.*\)/\1={{\1}}/p' ${{ inputs.sample-env-path }} > .env && cat .env

      - run: pnpm fetch --frozen-lockfile --prod=false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: pnpm install --frozen-lockfile --prod=false --ignore-scripts --offline
      - run: pnpm rebuild && pnpm run --if-present prepare

      - name: Build
        run: pnpm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Zip build folder
        run: pushd ${{ inputs.build-path }}; zip -q -r ../${{ inputs.artifact-name }}.zip *

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.working-directory }}/${{ inputs.artifact-name }}.zip
          if-no-files-found: error
