name: Python CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."
      install-algokit:
        required: false
        type: boolean
        default: true

jobs:
  check-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - uses: algorandfoundation/algokit-shared-config/.github/actions/setup-algokit-python@feat/python-release-workflow
        with:
          working-directory: ${{ inputs.working-directory }}
          install-algokit: ${{ inputs.install-algokit }}

      - name: Check pre-commits
        run: |
          set -o pipefail
          uv run pre-commit run --all-files && git diff --exit-code

      - name: Check documentation
        run: |
          set -o pipefail
          uv run poe docs-test

      - name: Check wheels can be built
        run: |
          set -o pipefail
          uv build --wheel

  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Setup Python and algokit
        uses: algorandfoundation/algokit-shared-config/.github/actions/setup-algokit-python@feat/python-release-workflow
        with:
          working-directory: ${{ inputs.working-directory }}
          install-algokit: ${{ inputs.install-algokit }}

      - name: pytest + coverage
        shell: bash
        env:
          COVERAGE_CORE: sysmon
        run: |
          set -o pipefail
          uv run pytest --junitxml=pytest-junit.xml --cov | tee pytest-coverage.txt

      - name: pytest coverage comment
        continue-on-error: true
        uses: MishaKav/pytest-coverage-comment@v1.2.0
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest-junit.xml
